<div class="col-sm-10">
    <div class="widget-box transparent">
        <div class="widget-header widget-header-flat">
            <h4 class="lighter">
                <i class="icon-star orange"></i>
                模块管理
            </h4>

            <div class="widget-toolbar">
                <a href="#" data-action="collapse">
                    <i class="icon-chevron-up"></i>
                </a>
            </div>
        </div>

        <div class="widget-body">
            <div class="widget-main no-padding">
                <table class="table table-bordered table-striped">
                    <thead class="thin-border-bottom">
                    <tr>
                        <th>
                            <i class="icon-caret-right blue"></i>
                            名字
                        </th>

                        <th>
                            <i class="icon-caret-right blue"></i>
                            描述
                        </th>

                        <th class="hidden-480">
                            <i class="icon-caret-right blue"></i>
                            状态
                        </th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <td>internet.com</td>

                        <td>
                            <small>
                                <s class="red">$29.99</s>
                            </small>
                            <b class="green">$19.99</b>
                        </td>

                        <td class="hidden-480">
                            <span class="label label-info arrowed-right arrowed-in">正常使用</span>
                        </td>
                    </tr>

                    <tr>
                        <td>online.com</td>

                        <td>
                            <small>
                                <s class="red"></s>
                            </small>
                            <b class="green">$16.45</b>
                        </td>

                        <td class="hidden-480">
                            <span class="label label-success arrowed-in arrowed-in-right">启用</span>
                        </td>
                    </tr>

                    <tr>
                        <td>newnet.com</td>

                        <td>
                            <small>
                                <s class="red"></s>
                            </small>
                            <b class="green">$15.00</b>
                        </td>

                        <td class="hidden-480">
                            <span class="label label-danger arrowed">已停用</span>
                        </td>
                    </tr>

                    <tr>
                        <td>web.com</td>

                        <td>
                            <small>
                                <s class="red">$24.99</s>
                            </small>
                            <b class="green">$19.95</b>
                        </td>

                        <td class="hidden-480">
																	<span class="label arrowed">
																		<s>已卸载</s>
																	</span>
                        </td>
                    </tr>

                    </tbody>
                </table>
            </div><!-- /widget-main -->
        </div><!-- /widget-body -->
    </div><!-- /widget-box -->
</div>