

<!-- 这里显示 网站截图 -->
<div class="bs-example overHidden clearBoth  layoutCenter" style="max-width:600px;" >
 <div style="padding:10px;border:5px solid #eee;margin-top:100px;" >
            <div style="margin-bottom:30px;border-bottom:3px solid #ddd;">
                <h4><?=$title?><small style="color:#ccc">提示信息</small></h4>
            </div>
            <div class="single-panel-body">
                <div class="single-panel-section" ng-show="show_signup">
                    <div class="form-group " >
                        <label class="text-left col-xs-10 ">
                            <?php
                            /*
                            if(false ==strpos($content,'=')){
                                echo $content;
                            }
                            else{
                                parse_str($content, $out);
                                var_dump($out);
                                if($out['content'])
                                    echo $out['content'];
                                if($out['js'])
                                    echo '<'
                            }
                            */
                            ?>
                        </label>
                    </div>
                    <div class="form-group">
                        <button id="returnBtn" class="btn-block btn btn-success">好</button>
                    </div>
                </div>
            </div>
</div>
</div><!-- .rowParent end -->
    <script src="/static/faltui/js/jquery-1.8.3.min.js"></script>
    <script src="/static/faltui/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/static/faltui/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/static/faltui/js/bootstrap.min.js"></script>
    <script src="/static/faltui/js/bootstrap-select.js"></script>
    <script src="/static/faltui/js/bootstrap-switch.js"></script>
    <script src="/static/faltui/js/flatui-checkbox.js"></script>
    <script src="/static/faltui/js/flatui-radio.js"></script>
    <script src="/static/faltui/js/jquery.tagsinput.js"></script>
    <script src="/static/faltui/js/jquery.placeholder.js"></script>
    <script src="/static/faltui/js/typeahead.js"></script>
    <script src="/static/faltui/bootstrap/js/google-code-prettify/prettify.js"></script>
    <script src="/static/faltui/js/application.js"></script>
    <script src="/static/default/js/validate.js"></script>
<script>
    <?php
        echo str_replace(['js://','php://'],['',''],$callback);
    ?>
</script>
