<div class="main-content">
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="icon-home home-icon"></i>
								<a href="#">Home</a>
							</li>

							<li>
								<a href="#">Forms</a>
							</li>
							<li class="active">Form Elements</li>
						</ul><!-- .breadcrumb -->

						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off">
									<i class="icon-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- #nav-search -->
					</div>

					<div class="page-content">
						<div class="page-header">
							<h1>
								栏目管理
								<small>
									<i class="icon-double-angle-right"></i>
									添加栏目
								</small>
							</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->

								<div class="form-horizontal" role="form">
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right">栏目等级</label>

										<div class="col-sm-9">
											<span class="input-icon">
												<select class="category_pid" name="category_pid" id="" >
													<option value="0">独立栏目</option>
													<option value="0">独立栏目</option>
													<option value="0">独立栏目</option>
												</select>
											</span>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right">栏目名字</label>
										<div class="col-sm-9">
											<span class="input-icon">
												<input class="category_name" type="text" id="form-field-icon-1">
												<i class="icon-terminal blue"></i>
											</span>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right">栏目地址</label>
										<div class="col-sm-9">
											<span class="input-icon">
												<input class="category_url" type="text" id="form-field-icon-1">
												<i class="icon-terminal blue"></i>
											</span>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-3 control-label no-padding-right">排序</label>
										<div class="col-sm-9">
											<span class="input-icon">
												<input class="category_sort" type="text" id="form-field-icon-1">
												<i class="icon-terminal blue"></i>
											</span>
										</div>
									</div>
									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="sub btn btn-info" type="button">
												<i class="icon-ok bigger-110"></i>
												提交
											</button>
											&nbsp; &nbsp; &nbsp;
											<button class="btn" type="reset">
												<i class="icon-undo bigger-110"></i>
												重置
											</button>
										</div>
									</div>
								</div>
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div>
<script>
	$(document).ready(function(){
		function getALlCategory() {
			$.ajax({
				url:"/admin/category/result",
				success:function(data){

				}
			})
		}
		$('.sub').click(function(){
			var url = $('.category_url').val(),
				name = $('.category_name').val(),
				pid = $('.category_pid').val(),
				sort = $('.category_sort').val();
			$.ajax({
				url:"add",
				type:'post',
				dataType:'json',
				data:{name:name,url:url,pid:pid,sort:sort},
				success:function(data)
				{
					if(data.type == 'success')
					{
						$('.category_url').val('');
						$('.category_name').val('');
						$('.category_pid').val('');
						$('.category_sort').val('');
					}
					else
					{
						//code somthing
					}
				}
			})
		})
	})
</script>