<div class="main-content">
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="icon-home home-icon"></i>
								<a href="#">Home</a>
							</li>

							<li>
								<a href="#">Forms</a>
							</li>
							<li class="active">Form Elements</li>
						</ul><!-- .breadcrumb -->

						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off">
									<i class="icon-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- #nav-search -->
					</div>

					<div class="page-content">
						<div class="page-header">
							<h1>
								栏目管理
								<small>
									<i class="icon-double-angle-right"></i>
									添加栏目
								</small>
							</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->

								<div class="form-horizontal" role="form">
									<div class="form-group">
										<label class="col-sm-2 control-label no-padding-right">商品分类</label>

										<div class="col-sm-9">
											<span class="">
												<select name="" id="">
													<option value="">1</option>
													<option value="">1</option>
													<option value="">1</option>
													<option value="">1</option>
												</select>
												<i class=""></i>
											</span>

										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 control-label no-padding-right">同类商品</label>

										<div class="col-sm-9">
											<span class="">
												<select name="" id="">
													<option value="">1</option>
													<option value="">1</option>
													<option value="">1</option>
													<option value="">1</option>
												</select>
												<i class=""></i>
											</span>

										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 control-label no-padding-right">商品名字</label>

										<div class="col-sm-9">
											<span class="input-icon">
												<input class="name" type="text" id="form-field-icon-1">
												<i class="icon-terminal blue"></i>
											</span>

										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 control-label no-padding-right">商品图片</label>

										<div class="col-sm-9">
											<span class="">
												<input type="file" multiple="1" />
											</span>

										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 control-label no-padding-right">折扣价</label>

										<div class="col-sm-9">
											<span class="input-icon">
												<input class="url" type="text" id="form-field-icon-1">
												<i class="icon-terminal blue"></i>
											</span>

										</div>
									</div>

									<div class="form-group">
										<label class="col-sm-2 control-label no-padding-right">库存</label>
										<div class="col-sm-9">
											<span class="input-icon">
												<input class="name" type="text" id="form-field-icon-1">
												<i class="icon-terminal blue"></i>
											</span>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 control-label no-padding-right">商品描述</label>
										<div class="col-sm-9">
											<span class="input-icon">
												<textarea name="" id=""  cols="50" rows="10"></textarea>
												<i class="icon-terminal blue"></i>
											</span>

										</div>
									</div>

									<div class="clearfix form-actions">
										<div class="col-md-offset-3 col-md-9">
											<button class="sub btn btn-info" type="button">
												<i class="icon-ok bigger-110"></i>
												提交
											</button>

											&nbsp; &nbsp; &nbsp;
											<button class="btn" type="reset">
												<i class="icon-undo bigger-110"></i>
												重置
											</button>
										</div>
									</div>
								</div>
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->


